### ISSUE TITLE
`XPST0017` error when using functions

### ISSUE THREAD

**Issue by DetachHead** [ilinsky/xpath.js#15]
```js
const xpath = require("xpath2.js");
const xmldom = require("xmldom");
const document = new xmldom.DOMParser().parseFromString("<div><button>Click me</button></div>");
const result = xpath.evaluate("//button[starts-with(., 'Click')]", document);
```
```
> node a.js

C:\project\node_modules\xpath2.js\lib\expressions\primary\FunctionCall.js:71
        throw new cException("XPST0017"
        ^
Error
    at Object.<anonymous> (C:\project\node_modules\xpath2.js\lib\classes\Exception.js:17:24)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\project\node_modules\xpath2.js\lib\types\schema\simple\atomic\XSDateTime.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) {
  code: 'XPST0017',
  message: 'Unknown user function: starts-with()'
}
```

**Comment by DetachHead** [comment]
nvm i didn't realize i had to set these:
```ts
const staticContext = xpath.createStaticContext()
staticContext.defaultFunctionNamespace = 'http://www.w3.org/2005/xpath-functions'
staticContext.defaultElementNamespace = '*'
```
